//Given two strings s and t which consist of only lowercase letters.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Find the letter that was added in t.

public class Leetcode389 {
    public static void main(String args[]) {

    }

    public char findTheDifference(String s, String t) {
        int[] map = new int[128];
        for(char ch : s.toCharArray()) {
            map[ch]++;
        }
        for(char ch : t.toCharArray()) {
            if(--map[ch] < 0) {
                return ch;
            }
        }

        return ' ';
    }

}
